// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using LDS.Domain.Models;

namespace LDS.Infrastructure.Context;

public partial class LDSContext : DbContext
{
    public LDSContext(DbContextOptions<LDSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LdsArea> LdsAreas { get; set; }

    public virtual DbSet<LdsBrand> LdsBrands { get; set; }

    public virtual DbSet<LdsCategory> LdsCategories { get; set; }

    public virtual DbSet<LdsPriceHistory> LdsPriceHistories { get; set; }

    public virtual DbSet<LdsProduct> LdsProducts { get; set; }

    public virtual DbSet<LdsUnitMeasure> LdsUnitMeasures { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LdsArea>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_Areas_Id");

            entity.ToTable("LDS_Areas");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsBrand>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_Brands_Id");

            entity.ToTable("LDS_Brands");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_Categories_Id");

            entity.ToTable("LDS_Categories");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsPriceHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_PriceHistory_Id");

            entity.ToTable("LDS_PriceHistory");

            entity.HasIndex(e => new { e.ProductId, e.StartDate }, "UQ_LDS_PriceHistory_Product_Date").IsUnique();

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.LdsPriceHistories)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LDS_PriceHistory_Product");
        });

        modelBuilder.Entity<LdsProduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_Products_Id");

            entity.ToTable("LDS_Products");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Quantity).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Area).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.AreaId)
                .HasConstraintName("FK_LDS_Products_Area");

            entity.HasOne(d => d.Brand).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_LDS_Products_Brand");

            entity.HasOne(d => d.Category).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_LDS_Products_Category");

            entity.HasOne(d => d.UnitMeasure).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.UnitMeasureId)
                .HasConstraintName("FK_LDS_Products_UnitMeasure");
        });

        modelBuilder.Entity<LdsUnitMeasure>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LDS_UnitMeasures_Id");

            entity.ToTable("LDS_UnitMeasures");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}