// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LDS.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace LDS.Infrastructure.Context;

public partial class LDSContext : DbContext
{
    public LDSContext(DbContextOptions<LDSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LdsArea> LdsAreas { get; set; }

    public virtual DbSet<LdsBrand> LdsBrands { get; set; }

    public virtual DbSet<LdsCategory> LdsCategories { get; set; }

    public virtual DbSet<LdsPriceHistory> LdsPriceHistories { get; set; }

    public virtual DbSet<LdsProduct> LdsProducts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LdsArea>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LDS_Area__3214EC0770C880C0");

            entity.ToTable("LDS_Areas");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsBrand>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LDS_Bran__3214EC07D737944F");

            entity.ToTable("LDS_Brands");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LDS_Cate__3214EC07924BE1B9");

            entity.ToTable("LDS_Categories");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LdsPriceHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LDS_Pric__3214EC079B5EA5C6");

            entity.ToTable("LDS_PriceHistory");

            entity.HasIndex(e => new { e.ProductId, e.StartDate }, "UQ_LDS_PriceHistory_Product_Date").IsUnique();

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.LdsPriceHistories)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LDS_PriceHistory_Product");
        });

        modelBuilder.Entity<LdsProduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LDS_Prod__3214EC070ACCA550");

            entity.ToTable("LDS_Products");

            entity.Property(e => e.BaseName).HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Quantity).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Unit).HasMaxLength(20);

            entity.HasOne(d => d.Area).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.AreaId)
                .HasConstraintName("FK_LDS_Products_Area");

            entity.HasOne(d => d.Brand).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_LDS_Products_Brand");

            entity.HasOne(d => d.Category).WithMany(p => p.LdsProducts)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_LDS_Products_Category");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}