// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LDS.Domain.Models;

public partial class LdsCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<LdsProduct> LdsProducts { get; set; } = new List<LdsProduct>();
}