// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LDS.Domain.Models;

public partial class LdsProduct
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? BrandId { get; set; }

    public int? CategoryId { get; set; }

    public int? AreaId { get; set; }

    public string ImageUrl { get; set; }

    public string BaseName { get; set; }

    public decimal? Quantity { get; set; }

    public string Unit { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual LdsArea Area { get; set; }

    public virtual LdsBrand Brand { get; set; }

    public virtual LdsCategory Category { get; set; }

    public virtual ICollection<LdsPriceHistory> LdsPriceHistories { get; set; } = new List<LdsPriceHistory>();
}